//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KEYSAPP.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class KeysDB {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KeysDB() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KEYSAPP.Resources.KeysDB", typeof(KeysDB).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2000.
        /// </summary>
        internal static string KEY1 {
            get {
                return ResourceManager.GetString("KEY1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3123.
        /// </summary>
        internal static string KEY10 {
            get {
                return ResourceManager.GetString("KEY10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 127.
        /// </summary>
        internal static string KEY100 {
            get {
                return ResourceManager.GetString("KEY100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1672.
        /// </summary>
        internal static string KEY11 {
            get {
                return ResourceManager.GetString("KEY11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2014.
        /// </summary>
        internal static string KEY12 {
            get {
                return ResourceManager.GetString("KEY12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1520.
        /// </summary>
        internal static string KEY13 {
            get {
                return ResourceManager.GetString("KEY13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3232.
        /// </summary>
        internal static string KEY14 {
            get {
                return ResourceManager.GetString("KEY14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2008.
        /// </summary>
        internal static string KEY15 {
            get {
                return ResourceManager.GetString("KEY15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string KEY16 {
            get {
                return ResourceManager.GetString("KEY16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 209.
        /// </summary>
        internal static string KEY17 {
            get {
                return ResourceManager.GetString("KEY17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1010.
        /// </summary>
        internal static string KEY18 {
            get {
                return ResourceManager.GetString("KEY18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3455.
        /// </summary>
        internal static string KEY19 {
            get {
                return ResourceManager.GetString("KEY19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 50.
        /// </summary>
        internal static string KEY2 {
            get {
                return ResourceManager.GetString("KEY2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 314.
        /// </summary>
        internal static string KEY20 {
            get {
                return ResourceManager.GetString("KEY20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 5504.
        /// </summary>
        internal static string KEY21 {
            get {
                return ResourceManager.GetString("KEY21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1064.
        /// </summary>
        internal static string KEY22 {
            get {
                return ResourceManager.GetString("KEY22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1986.
        /// </summary>
        internal static string KEY23 {
            get {
                return ResourceManager.GetString("KEY23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 301.
        /// </summary>
        internal static string KEY24 {
            get {
                return ResourceManager.GetString("KEY24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 89.
        /// </summary>
        internal static string KEY25 {
            get {
                return ResourceManager.GetString("KEY25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1961.
        /// </summary>
        internal static string KEY26 {
            get {
                return ResourceManager.GetString("KEY26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 404.
        /// </summary>
        internal static string KEY27 {
            get {
                return ResourceManager.GetString("KEY27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 000.
        /// </summary>
        internal static string KEY28 {
            get {
                return ResourceManager.GetString("KEY28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 8571.
        /// </summary>
        internal static string KEY29 {
            get {
                return ResourceManager.GetString("KEY29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2926.
        /// </summary>
        internal static string KEY3 {
            get {
                return ResourceManager.GetString("KEY3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 79.
        /// </summary>
        internal static string KEY30 {
            get {
                return ResourceManager.GetString("KEY30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 8192.
        /// </summary>
        internal static string KEY31 {
            get {
                return ResourceManager.GetString("KEY31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 17.
        /// </summary>
        internal static string KEY32 {
            get {
                return ResourceManager.GetString("KEY32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3310.
        /// </summary>
        internal static string KEY33 {
            get {
                return ResourceManager.GetString("KEY33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 365.
        /// </summary>
        internal static string KEY34 {
            get {
                return ResourceManager.GetString("KEY34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 007.
        /// </summary>
        internal static string KEY35 {
            get {
                return ResourceManager.GetString("KEY35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 410.
        /// </summary>
        internal static string KEY36 {
            get {
                return ResourceManager.GetString("KEY36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 747.
        /// </summary>
        internal static string KEY37 {
            get {
                return ResourceManager.GetString("KEY37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3433.
        /// </summary>
        internal static string KEY38 {
            get {
                return ResourceManager.GetString("KEY38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 10.
        /// </summary>
        internal static string KEY39 {
            get {
                return ResourceManager.GetString("KEY39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1111.
        /// </summary>
        internal static string KEY4 {
            get {
                return ResourceManager.GetString("KEY4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2012.
        /// </summary>
        internal static string KEY40 {
            get {
                return ResourceManager.GetString("KEY40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0214.
        /// </summary>
        internal static string KEY41 {
            get {
                return ResourceManager.GetString("KEY41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4263.
        /// </summary>
        internal static string KEY42 {
            get {
                return ResourceManager.GetString("KEY42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 29.
        /// </summary>
        internal static string KEY43 {
            get {
                return ResourceManager.GetString("KEY43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1991.
        /// </summary>
        internal static string KEY44 {
            get {
                return ResourceManager.GetString("KEY44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 666.
        /// </summary>
        internal static string KEY45 {
            get {
                return ResourceManager.GetString("KEY45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 852.
        /// </summary>
        internal static string KEY46 {
            get {
                return ResourceManager.GetString("KEY46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 5030.
        /// </summary>
        internal static string KEY47 {
            get {
                return ResourceManager.GetString("KEY47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3000.
        /// </summary>
        internal static string KEY48 {
            get {
                return ResourceManager.GetString("KEY48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 34.
        /// </summary>
        internal static string KEY49 {
            get {
                return ResourceManager.GetString("KEY49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 8848.
        /// </summary>
        internal static string KEY5 {
            get {
                return ResourceManager.GetString("KEY5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 356.
        /// </summary>
        internal static string KEY50 {
            get {
                return ResourceManager.GetString("KEY50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 119.
        /// </summary>
        internal static string KEY51 {
            get {
                return ResourceManager.GetString("KEY51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 360.
        /// </summary>
        internal static string KEY52 {
            get {
                return ResourceManager.GetString("KEY52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 81.
        /// </summary>
        internal static string KEY53 {
            get {
                return ResourceManager.GetString("KEY53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 5778.
        /// </summary>
        internal static string KEY54 {
            get {
                return ResourceManager.GetString("KEY54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 5.
        /// </summary>
        internal static string KEY55 {
            get {
                return ResourceManager.GetString("KEY55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 7108.
        /// </summary>
        internal static string KEY56 {
            get {
                return ResourceManager.GetString("KEY56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 134.
        /// </summary>
        internal static string KEY57 {
            get {
                return ResourceManager.GetString("KEY57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 100.
        /// </summary>
        internal static string KEY58 {
            get {
                return ResourceManager.GetString("KEY58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 20.
        /// </summary>
        internal static string KEY59 {
            get {
                return ResourceManager.GetString("KEY59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2048.
        /// </summary>
        internal static string KEY6 {
            get {
                return ResourceManager.GetString("KEY6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 17.
        /// </summary>
        internal static string KEY60 {
            get {
                return ResourceManager.GetString("KEY60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 88.
        /// </summary>
        internal static string KEY61 {
            get {
                return ResourceManager.GetString("KEY61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 033.
        /// </summary>
        internal static string KEY62 {
            get {
                return ResourceManager.GetString("KEY62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1945.
        /// </summary>
        internal static string KEY63 {
            get {
                return ResourceManager.GetString("KEY63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1920.
        /// </summary>
        internal static string KEY64 {
            get {
                return ResourceManager.GetString("KEY64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 9806.
        /// </summary>
        internal static string KEY65 {
            get {
                return ResourceManager.GetString("KEY65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 54.
        /// </summary>
        internal static string KEY66 {
            get {
                return ResourceManager.GetString("KEY66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 47.
        /// </summary>
        internal static string KEY67 {
            get {
                return ResourceManager.GetString("KEY67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 24.
        /// </summary>
        internal static string KEY68 {
            get {
                return ResourceManager.GetString("KEY68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 545.
        /// </summary>
        internal static string KEY69 {
            get {
                return ResourceManager.GetString("KEY69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 9696.
        /// </summary>
        internal static string KEY7 {
            get {
                return ResourceManager.GetString("KEY7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1914.
        /// </summary>
        internal static string KEY70 {
            get {
                return ResourceManager.GetString("KEY70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 101.
        /// </summary>
        internal static string KEY71 {
            get {
                return ResourceManager.GetString("KEY71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 72.
        /// </summary>
        internal static string KEY72 {
            get {
                return ResourceManager.GetString("KEY72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 8.
        /// </summary>
        internal static string KEY73 {
            get {
                return ResourceManager.GetString("KEY73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1947.
        /// </summary>
        internal static string KEY74 {
            get {
                return ResourceManager.GetString("KEY74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1937.
        /// </summary>
        internal static string KEY75 {
            get {
                return ResourceManager.GetString("KEY75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 10.
        /// </summary>
        internal static string KEY76 {
            get {
                return ResourceManager.GetString("KEY76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 01.
        /// </summary>
        internal static string KEY77 {
            get {
                return ResourceManager.GetString("KEY77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 20.
        /// </summary>
        internal static string KEY78 {
            get {
                return ResourceManager.GetString("KEY78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 75.
        /// </summary>
        internal static string KEY79 {
            get {
                return ResourceManager.GetString("KEY79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2342.
        /// </summary>
        internal static string KEY8 {
            get {
                return ResourceManager.GetString("KEY8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 739.
        /// </summary>
        internal static string KEY80 {
            get {
                return ResourceManager.GetString("KEY80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 35.
        /// </summary>
        internal static string KEY81 {
            get {
                return ResourceManager.GetString("KEY81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 350.
        /// </summary>
        internal static string KEY82 {
            get {
                return ResourceManager.GetString("KEY82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 8694.
        /// </summary>
        internal static string KEY83 {
            get {
                return ResourceManager.GetString("KEY83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4377.
        /// </summary>
        internal static string KEY84 {
            get {
                return ResourceManager.GetString("KEY84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 13.
        /// </summary>
        internal static string KEY85 {
            get {
                return ResourceManager.GetString("KEY85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 269.
        /// </summary>
        internal static string KEY86 {
            get {
                return ResourceManager.GetString("KEY86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 8382.
        /// </summary>
        internal static string KEY87 {
            get {
                return ResourceManager.GetString("KEY87", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 9.
        /// </summary>
        internal static string KEY88 {
            get {
                return ResourceManager.GetString("KEY88", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 958.
        /// </summary>
        internal static string KEY89 {
            get {
                return ResourceManager.GetString("KEY89", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1980.
        /// </summary>
        internal static string KEY9 {
            get {
                return ResourceManager.GetString("KEY9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 64.
        /// </summary>
        internal static string KEY90 {
            get {
                return ResourceManager.GetString("KEY90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 452.
        /// </summary>
        internal static string KEY91 {
            get {
                return ResourceManager.GetString("KEY91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 39.
        /// </summary>
        internal static string KEY92 {
            get {
                return ResourceManager.GetString("KEY92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 121.
        /// </summary>
        internal static string KEY93 {
            get {
                return ResourceManager.GetString("KEY93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 240.
        /// </summary>
        internal static string KEY94 {
            get {
                return ResourceManager.GetString("KEY94", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2015.
        /// </summary>
        internal static string KEY95 {
            get {
                return ResourceManager.GetString("KEY95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 102.
        /// </summary>
        internal static string KEY96 {
            get {
                return ResourceManager.GetString("KEY96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 7.
        /// </summary>
        internal static string KEY97 {
            get {
                return ResourceManager.GetString("KEY97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1492.
        /// </summary>
        internal static string KEY98 {
            get {
                return ResourceManager.GetString("KEY98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 88.
        /// </summary>
        internal static string KEY99 {
            get {
                return ResourceManager.GetString("KEY99", resourceCulture);
            }
        }
    }
}
